# Python package
# Create and test a Python package on multiple Python versions.
# Add steps that analyze code, save the dist with the build record, publish to a PyPI-compatible index, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/python

trigger:
  branches:
    include:
    - master
  paths:
    exclude:
    - 'docs/*'
    - 'static/assets/'
    - 'README.md'
    - '**/*.md'

pr:
  autoCancel: true
  paths:
    exclude:
    - 'README.md'

pool:
  vmImage: ubuntu-latest
strategy:
  matrix:
    Python39:
      python.version: '3.9'

env:
    ACCESS_TOKEN_EXPIRES: $(ACCESS_TOKEN_EXPIRES)
    JWT_ALGO: $(JWT_ALGO)
    JWT_SECRET: $(JWT_SECRET)

steps:
- task: UsePythonVersion@0
  inputs:
    versionSpec: '$(python.version)'
  displayName: 'Use Python $(python.version)'

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- script: |
    pip install pytest pytest-azurepipelines
    python -m pytest tests/
  displayName: 'pytest'

- script: |
    safety check -r requirements.txt
  displayName: 'Dependency Check Safety'

